### ISSUE TITLE
metamask 'wrong network'

### ISSUE THREAD

**Issue by goblinscash** [goblinscash/bch-front#1]
not prompting metamask to connect when you're on the wrong network and click 'wrong network' button in header

**Comment by ragnokg** [comment]
if you're not connected to smartBCH, the wrong network button should trigger metamask to connect to smartBCH. it triggers a browser popup but never triggers Metamask to switch to the right network. someone in telegram said it looked like we were using depricated metamask api?

![image](https://user-images.githubusercontent.com/99830341/154328823-de68ac55-fd6a-4555-a454-2af2d27d6c1c.png)
