### ISSUE TITLE
AmplePro Bonds

### ISSUE THREAD

**Issue by ragnokg** [goblinscash/bch-front#5]
New bond type 'pro' on front end that can handle bonds w/ different payout tokens. The UX will be the same as our current bonds but will need the following to function:
1. payout token name will come from bond settings (needs to be added)
2. market price will come from getGoldPrice() (oracle.sol contract; 0x9c3ED1A6B079BA8a2a0F047ed69b9402c0347b16 on amber testnet)
3. will also need a variable in bond settings for 'treasury' address as these new bonds will use a different treasury. this will be needed to report on holdings in the dashboard.
4. edit current bond page to have separate blocks for each bond type (similar to what hector dao has done https://app.hector.finance/#/bonds). essentially one block at top for current bonds and one block below for new pro bonds.

Proposed changes for pro bonds in src/helpers/bond/index.ts:
```javascript
export const gob_flexusd_pro = new **ProBond**({ **//new bond type 'ProBond'- price coming from getGoldPrice() instead of LP reserves**
    name: "gob_flexusd_pro",
    displayName: "GOB-flexUSD LP",
    **payoutTokenName**: "gBCH",  **//new field 'payoutToken' - will show on /mints pages**
    bondToken: "fUSD",
    bondIconSvg: FusdGobIcon,
    bondContractABI: **ProBondContract**, **//new abi for pro bonds**
    reserveContractAbi: LpReserveContract,
    networkAddrs: {
        [Networks.AMBER]: {
            bondAddress: "0x9C122F45aE24767Df7cfAC347Cd96cF3d3655Bea",
            reserveAddress: "0x9b9190C5392116a865Ceef53b57b0bb758256f74",
            **proTreasuryAddress**: "0xC3717BC5Ec2332f040a52C5b9d125aECc21f2d33", **//new treasury field for pro bonds**
        },
    },
    lpUrl: "https://app.mistswap.fi/add/0xEA48ca36933873507636e4aFD72a74f612aAf8CD/0x96917995f030f8fC3D8fDF40F3a6422547c877c1",
});
```

**Comment by ragnokg** [comment]
[Ample and Pro Contracts.zip](https://github.com/goblinscash/bch-front/files/8118459/Ample.and.Pro.Contracts.zip)
[testnet addresses.txt](https://github.com/goblinscash/bch-front/files/8118460/testnet.addresses.txt)
How to launch bonds w/ elastic token https://docs.google.com/document/d/1gG4FjZp07xUwhE6T6XO-bBo1hdAmBidPJO2oqkqgtxo/edit?usp=sharing

**Comment by trankuilized** [comment]
oracle abi - used to get current token price - getGoldPrice()
[oracle.txt](https://github.com/goblinscash/bch-front/files/8171089/oracle.txt)

bond abi 
[bond.txt](https://github.com/goblinscash/bch-front/files/8171130/bond.txt)

treasury abi 
[treasury.txt](https://github.com/goblinscash/bch-front/files/8171144/treasury.txt)

**Comment by trankuilized** [comment]
bond abi
[bond.txt](https://github.com/goblinscash/bch-front/files/8171127/bond.txt)

**Comment by trankuilized** [comment]
Bond Purchase
Mint
prices - do they not show decimals? (on mint & redeem)
all "GOB" references should be replaced w/ payout token for bond
time til fully vested not working

Redeem
"Your balance" pulling bond name, not token name
Remove "claim and autostake"


Gold and market prices are flipped :)

"you will get" nan
